<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="review"
    nsURI="http://jutzig.de/jabylon/review" nsPrefix="review">
  <eClassifiers xsi:type="ecore:EClass" name="PropertyFileReview">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyFile" eType="ecore:EClass ../../de.jutzig.jabylon.properties/model/properties.ecore#//PropertyFileDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviews" upperBound="-1"
        eType="#//Review" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Review">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" eType="#//Comment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ReviewState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reviewType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//Severity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReviewState">
    <eLiterals name="OPEN" literal="OPEN"/>
    <eLiterals name="RESOLVED" value="1"/>
    <eLiterals name="INVALID" value="2"/>
    <eLiterals name="REOPENED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Severity">
    <eLiterals name="INFO"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="ERROR" value="2"/>
  </eClassifiers>
</ecore:EPackage>
