/** 
 * https://github.com/jutzig/jabylon/issues/97
 * https://github.com/jutzig/jabylon/issues/145 
 * while we are at it, it makes sense to trim the other columns to reasonable values*/
ALTER TABLE USER0 ADD "TOKEN" varchar(32) NULL ;
ALTER TABLE USER0 ALTER "NAME" VARCHAR(255);
ALTER TABLE USER0 ALTER "PASSWORD" VARCHAR(255);
ALTER TABLE USER0 ALTER "DISPLAYNAME" VARCHAR(255);
ALTER TABLE USER0 ALTER "TYPE" VARCHAR(255);
ALTER TABLE USER0 ALTER "EMAIL" VARCHAR(255);
ALTER TABLE ROLE0 ALTER "NAME" VARCHAR(255);
ALTER TABLE PERMISSION ALTER "NAME" VARCHAR(255);
ALTER TABLE PERMISSION ALTER "DESCRIPTION" VARCHAR(1024);
ALTER TABLE AUTHTYPE ALTER "NAME" VARCHAR(255);
ALTER TABLE AUTHTYPE ALTER "AUTHMODULE" VARCHAR(255);
ALTER TABLE PROJECT ALTER "REPOSITORYURI" VARCHAR(1024);
ALTER TABLE PROJECT ALTER "NAME" VARCHAR(255);
ALTER TABLE PROJECT ALTER "TEAMPROVIDER" VARCHAR(32);
ALTER TABLE PROJECTVERSION ALTER "NAME" VARCHAR(255);
ALTER TABLE PROJECTLOCALE ALTER "NAME" VARCHAR(255);
ALTER TABLE PROJECTLOCALE ALTER "LOCALE" VARCHAR(32);
ALTER TABLE PROPERTYFILEDESCRIPTOR ALTER "VARIANT" VARCHAR(32);
ALTER TABLE PROPERTYFILEDESCRIPTOR ALTER "NAME" VARCHAR(255);
ALTER TABLE PROPERTYFILEDESCRIPTOR ALTER "LOCATION" VARCHAR(1024);
ALTER TABLE RESOURCEFOLDER ALTER "NAME" VARCHAR(255);
ALTER TABLE REVIEW ALTER "MESSAGE" VARCHAR(1024);
ALTER TABLE REVIEW ALTER "USER0" VARCHAR(255);
ALTER TABLE REVIEW ALTER "REVIEWTYPE" VARCHAR(255);
ALTER TABLE REVIEW ALTER "KEY0" VARCHAR(1024);
ALTER TABLE COMMENT ALTER "USER0" VARCHAR(255);
ALTER TABLE COMMENT ALTER "MESSAGE" VARCHAR(1024);
ALTER TABLE WORKSPACE ALTER "NAME" VARCHAR(255);
ALTER TABLE WORKSPACE ALTER "ROOT" VARCHAR(1024);