package de.jutzig.jabylon.ui.components;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Resource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

import de.jutzig.jabylon.ui.resources.ImageConstants;

public class Section extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private GridLayout body;
	@AutoGenerated
	private HorizontalLayout header;
	@AutoGenerated
	private Button toggle;
	@AutoGenerated
	private Label sectionTitle;

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Section() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		header.setWidth(100, UNITS_PERCENTAGE);
		toggle.setIcon(ImageConstants.IMAGE_TWISTY_EXPANDED);
		toggle.setCaption("");
		toggle.addListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				Resource image = body.isVisible() ? ImageConstants.IMAGE_TWISTY_COLLAPSED :ImageConstants.IMAGE_TWISTY_EXPANDED; 
				body.setVisible(!body.isVisible());
				toggle.setIcon(image);
			}
		});
		sectionTitle.addStyleName("jabylon-section-label");
		body.setSizeFull();

		// TODO add user code here
	}

	public void setTitle(String title)
	{
		sectionTitle.setValue(title);
	}
	
	
	public GridLayout getBody() {
		return body;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);

		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		

		// header
		header = buildHeader();
		mainLayout.addComponent(header);
		mainLayout.setExpandRatio(header, 1.0f);
		
		// body
		body = new GridLayout();
		body.setImmediate(false);
		body.setMargin(false);
		mainLayout.addComponent(body);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHeader() {
		// common part: create layout
		header = new HorizontalLayout();
		header.setStyleName("jabylon-section-title");
		header.setImmediate(false);

		header.setMargin(false);
		
		// sectionTitle
		sectionTitle = new Label();
		sectionTitle.setImmediate(false);
		sectionTitle.setValue("Title");
		header.addComponent(sectionTitle);
		
		// toggle
		toggle = new Button();
		toggle.setStyleName("link");
		toggle.setCaption("Button");
		toggle.setImmediate(true);
		header.addComponent(toggle);
		header.setComponentAlignment(toggle, new Alignment(6));
		
		return header;
	}

}
