package de.jutzig.jabylon.ui.components;

import com.vaadin.ui.Panel;

public class Section extends Panel {

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Section() {

		setStyleName("bubble"); //$NON-NLS-1$

	}

}
